/**
 * Leoloso\GraphQLByPoPWPPlugin\Blocks\SchemaConfigOptionsBlock::ATTRIBUTE_VALUE_USE_NAMESPACING_DEFAULT
 */
const ATTRIBUTE_VALUE_USE_NAMESPACING_DEFAULT = 'default';
/**
 * Leoloso\GraphQLByPoPWPPlugin\Blocks\SchemaConfigOptionsBlock::ATTRIBUTE_VALUE_USE_NAMESPACING_ENABLED
 */
const ATTRIBUTE_VALUE_USE_NAMESPACING_ENABLED = 'enabled';
/**
 * Leoloso\GraphQLByPoPWPPlugin\Blocks\SchemaConfigOptionsBlock::ATTRIBUTE_VALUE_USE_NAMESPACING_DISABLED
 */
const ATTRIBUTE_VALUE_USE_NAMESPACING_DISABLED = 'disabled';

export {
	ATTRIBUTE_VALUE_USE_NAMESPACING_DEFAULT,
	ATTRIBUTE_VALUE_USE_NAMESPACING_ENABLED,
	ATTRIBUTE_VALUE_USE_NAMESPACING_DISABLED,
};
