<?php

declare(strict_types=1);

namespace GraphQLAPI\GraphQLAPI;

class Environment
{
    public const ADD_EXCERPT_AS_DESCRIPTION = 'ADD_EXCERPT_AS_DESCRIPTION';
    public const GROUP_FIELDS_UNDER_TYPE_FOR_PRINT = 'GROUP_FIELDS_UNDER_TYPE_FOR_PRINT';
    public const EMPTY_LABEL = 'EMPTY_LABEL';
    public const SETTINGS_VALUE_LABEL = 'SETTINGS_VALUE_LABEL';
    public const USE_GRAPHIQL_WITH_EXPLORER = 'USE_GRAPHIQL_WITH_EXPLORER';
    public const ENDPOINT_SLUG_BASE = 'ENDPOINT_SLUG_BASE';
    public const PERSISTED_QUERY_SLUG_BASE = 'PERSISTED_QUERY_SLUG_BASE';
    public const SCHEMA_EDITOR_ACCESS_SCHEME = 'SCHEMA_EDITOR_ACCESS_SCHEME';
    public const ENABLE_LOW_LEVEL_SCHEMA_EDITING = 'ENABLE_LOW_LEVEL_SCHEMA_EDITING';
}
